// Tech framework and service icons from react-icons
import {
  SiNextdotjs,
  SiVercel,
  SiPostgresql,
  SiReact,
  SiTypescript,
  SiTailwindcss,
  SiNodedotjs,
  SiPrisma,
  SiSupabase,
  SiAmazon,
  SiGooglecloud,
  SiMongodb,
  SiRedis,
  SiDocker,
  SiKubernetes,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiStripe,
  SiDrizzle,
  SiFirebase,
  SiPlanetscale,
  SiCloudflare,
  SiNetlify,
  SiRailway,
  SiVuedotjs,
  SiNuxtdotjs,
  SiGo,
  SiSqlite,
} from "react-icons/si";

// Export all tech icons with consistent naming
export const TechIcons = {
  NextJS: SiNextdotjs,
  Vercel: SiVercel,
  PostgreSQL: SiPostgresql,
  React: SiReact,
  TypeScript: SiTypescript,
  TailwindCSS: SiTailwindcss,
  NodeJS: SiNodedotjs,
  Prisma: SiPrisma,
  Supabase: SiSupabase,
  AWS: SiAmazon,
  GoogleCloud: SiGooglecloud,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Figma: SiFigma,
  Stripe: SiStripe,
  Drizzle: SiDrizzle,
  Firebase: SiFirebase,
  PlanetScale: SiPlanetscale,
  Cloudflare: SiCloudflare,
  Netlify: SiNetlify,
  Railway: SiRailway,
  Vue: SiVuedotjs,
  Nuxt: SiNuxtdotjs,
  Go: SiGo,
  SQLite: SiSqlite,
} as const;

// Individual exports for convenience
export {
  SiNextdotjs as NextJSIcon,
  SiVercel as VercelIcon,
  SiPostgresql as PostgreSQLIcon,
  SiReact as ReactIcon,
  SiTypescript as TypeScriptIcon,
  SiTailwindcss as TailwindIcon,
  SiNodedotjs as NodeJSIcon,
  SiPrisma as PrismaIcon,
  SiSupabase as SupabaseIcon,
  SiAmazon as AWSIcon,
  SiGooglecloud as GoogleCloudIcon,
  SiMongodb as MongoDBIcon,
  SiRedis as RedisIcon,
  SiDocker as DockerIcon,
  SiKubernetes as KubernetesIcon,
  SiGithub as GitHubIcon,
  SiGitlab as GitLabIcon,
  SiFigma as FigmaIcon,
  SiStripe as StripeIcon,
  SiDrizzle as DrizzleIcon,
  SiFirebase as FirebaseIcon,
  SiPlanetscale as PlanetScaleIcon,
  SiCloudflare as CloudflareIcon,
  SiNetlify as NetlifyIcon,
  SiRailway as RailwayIcon,
  SiVuedotjs as VueIcon,
  SiNuxtdotjs as NuxtIcon,
  SiGo as GoIcon,
  SiSqlite as SQLiteIcon,
};
